In [2]:
import numpy as np
import pandas as pd
from scipy.stats import norm
from scipy.stats import ttest_1samp, ttest_ind

In [10]:
df = pd.read_csv("C:/Users/htc/Downloads/Sachin_ODI.csv")

In [3]:
df.head()

runs  NotOut mins  bf  fours  sixes      sr  Inns           Opp    Ground  \
0    13       0   30  15      3      0   86.66     1   New Zealand    Napier   
1    37       0   75  51      3      1   72.54     2  South Africa  Hamilton   
2    47       0   65  40      7      0  117.50     2     Australia   Dunedin   
3    48       0   37  30      9      1  160.00     2    Bangladesh   Sharjah   
4     4       0   13   9      1      0   44.44     2      Pakistan   Sharjah   

         Date        Winner    Won  century  
0  1995-02-16   New Zealand  False    False  
1  1995-02-18  South Africa  False    False  
2  1995-02-22         India   True    False  
3  1995-04-05         India   True    False  
4  1995-04-07      Pakistan  False    False

In [7]:
mu = df['runs'].mean()
mu

43.24166666666667

In [10]:
sigma = df['runs'].std()
sigma 

42.18245206052441

In [19]:
first_innings_score = df.loc[df['Inns']==1][['runs']]

In [56]:
data = first_innings_score

In [57]:
# Null hypothesis : His first innings score is no better than the overall score.
# Alternate hypothesis : His first innings score is better than the overall score.

In [58]:
data.mean()

runs    46.670588
dtype: float64

In [59]:
z_stat = (data.mean()-mu)/(sigma/np.sqrt(len(data)))

In [60]:
z_stat

runs    1.059864
dtype: float64

In [61]:
p_value = 1-norm.cdf(z_stat)
p_value

array([0.14460321])

In [62]:
alpha = 0.05

In [63]:
if p_value < alpha:
    print('Reject Null Hypothesis')
else:
    print('Fail to reject Null Hypothesis')

Fail to reject Null Hypothesis


# His scoring pattern in Victory

In [52]:
data = df.loc[df['Won'] == True][['runs']]
data.head()

runs
2    47
3    48
5   112
6    41
8    39

In [53]:
data.mean()

runs    51.0
dtype: float64

In [54]:
z_stat = (data.mean()-mu)/(sigma/np.sqrt(len(data)))
z_stat

runs    2.494856
dtype: float64

In [55]:
p_value = 1-norm.cdf(z_stat)
p_value

array([0.00630041])

In [46]:
if p_value < alpha:
    print('Reject Null Hypothesis')
else:
    print('Fail to reject Null Hypothesis')

Reject Null Hypothesis


In [70]:
norm.cdf(-2.077327431147614)

0.01888567447570836

In [71]:
(6-5.41)/(1.1/np.sqrt(15))

2.077327431147614

In [72]:
norm.cdf(-1.761)

0.039119201499735363

In [73]:
x = 6 + (-1.761*(1.1/np.sqrt(15)))

In [74]:
x

5.499842930670774

In [75]:
(77.4-90)/(29.6/np.sqrt(9))

-1.2770270270270263

In [76]:
(1.85-1.7)/(0.5/np.sqrt(30))

1.6431676725155

In [78]:
(530-500)/(125/np.sqrt(70))

2.007984063681781

In [79]:
3.5+(1.28*(0.7/np.sqrt(45)))

3.6335677938559874

In [83]:
(30)/(125/np.sqrt(70))



2.007984063681781

## Improve IQ

In [3]:
iq_scores = [110,105,98,102,99,104,115,95]

In [4]:
np.mean(iq_scores)

103.5

H0: mu = 100
Ha: mu >100

In [5]:
alpha = 0.01

In [6]:
ttest_1samp(iq_scores,100)

TtestResult(statistic=1.5071573172061195, pvalue=0.1754994493585011, df=7)

In [7]:
t_stat,p_value = ttest_1samp(iq_scores,100)

In [8]:
t_stat,p_value

(1.5071573172061195, 0.1754994493585011)

In [9]:
if p_value < alpha:
    print('Reject H0')
else:
    print('Fail to Reject H0')

Fail to Reject H0


# First innings vs second innings

In [11]:
df_first_innings = df.loc[df['Inns']==1][['runs']]

In [12]:
df_first_innings.mean()

runs    46.670588
dtype: float64

In [13]:
df_second_innings = df.loc[df['Inns']==2][['runs']]

In [14]:
df_second_innings.mean()

runs    40.173684
dtype: float64

In [15]:
# Is this difference significant or by chance?

H0: mu1 = mu2,
Ha: mu1 > mu2

In [17]:
t_stat,p_value =ttest_ind(df_first_innings,df_second_innings,alternative = 'greater')

In [18]:
p_value

array([0.07241862])

In [19]:
alpha = 0.05

In [20]:
if p_value < alpha:
    print('Reject H0')
else:
    print('Fail to Reject H0')

Fail to Reject H0


# Victory vs Lose

In [26]:
df_won = df.loc[df['Won']==True][['runs']]

In [31]:
df_loss = df.loc[df['Won']==False][['runs']]

H0: mu1 = mu2 ,
Ha: mu1 > mu2

In [32]:
t_stat,p_value =ttest_ind(df_won,df_loss,alternative = 'greater')

In [33]:
p_value

array([0.00016353])

In [34]:
if p_value < alpha:
    print('Reject H0')
else:
    print('Fail to Reject H0')

Reject H0


## Problems

The average no. of customers entering a store everyday is 500, with a std of 125.
A marketing team claims to increase this number.
After 70 days, it is seen that the average is 530.
Test the claim of the marketing company at 95% confidence.

H0: mu = 500,
Ha: mu > 500

In [35]:
alpha = 0.05

In [37]:
z_stat = (530-500)/(125/np.sqrt(70))

In [39]:
p_value = 1 - norm.cdf(z_stat)

In [40]:
if p_value < alpha:
    print('Reject H0')
else:
    print('Fail to Reject H0')

Reject H0


A local football game sees 3.5 goals per match on average with std of 0.7 .
A sample of 45 matches was taken.
What should be the maximum average goals of these 45 matches such that we can continue to believe this statement that the population average is 3.5 goals at 10% significance?

H0: mu = 3.5,
Ha: mu >3.5

In [41]:
z_critical = norm.ppf(0.90)

In [42]:
z_critical

1.2815515655446004

In [43]:
x = 3.5 + (z_critical * 0.7/np.sqrt(45))

In [44]:
x

3.633729699470687

In [45]:
# If it is less than 3.633 we will continue to believe.

 The no. of hours a student spends solving assessment problems across two batches are known.
 Test if one batch takes lesser time , significance of 5%

In [46]:
batch_1 = pd.Series([25,30,45,49,47,35,32,42])
batch_2 = pd.Series([45,47,25,22,29,32,27,28,40,49,50,33])

H0: mu1 = mu2
Ha: mu1 > mu2

In [48]:
batch_1.mean()

38.125

In [49]:
batch_2.mean()

35.583333333333336

In [50]:
t_stat,p_value = ttest_ind(batch_1,batch_2,alternative = 'greater')

In [51]:
if p_value < alpha:
    print('Reject H0')
else:
    print('Fail to Reject H0')

Fail to Reject H0


H0: mu1 = mu2
Ha: mu1 > mu2

There are 8 females and 12 males in a coaching class. After a practice test, the coach wants to know whether the average score of females is greater than the average score of males.

Given data describes the scores of females and males. Check whether the assumption of the coach is significant or not at a 5% of significance level?


In [58]:
female_scores=pd.Series([25,30,45,49,47,35,32,42])

male_scores=pd.Series([45,47,25,22,29,32,27,28,40,49,50,33])

In [59]:
female_scores.mean()

38.125

In [60]:
male_scores.mean()

35.583333333333336

H0: mu1 = mu2,
Ha: mu1 > mu2

In [61]:
t_stat,p_value = ttest_ind(female_scores,male_scores,alternative = 'greater')

In [62]:
if p_value < alpha:
    print('Reject H0')
else:
    print('Fail to Reject H0')

Fail to Reject H0


An institution claims that the candidates who study there have more IQ than the average institution. When the IQ of 50 students was calculated, the average turned out to be 110.

The mean of the population IQ is 100 and the standard deviation is 15. Find the validity of the claim with a significance level of 5%.

H0 : mu = 100
Ha : mu > 100

In [66]:
alpha = 0.05

In [67]:
z_stat = (110-100)/(15/np.sqrt(50))

In [68]:
p_value = 1- norm.cdf(z_stat)

In [69]:
p_value

1.2142337364462463e-06

In [70]:
if p_value < alpha:
    print('Reject H0')
else:
    print('Fail to Reject H0')

Reject H0


The quality assurance department claims that on average the non-fat milk contains more than 190 mg of Calcium per 500 ml packet.

To check this claim 45 packets of milk are collected and the content of calcium is recorded. perform the appropriate test with 90% confidence.


In [78]:
data = pd.Series([193, 321, 222, 158, 176, 149, 154, 223, 233, 177, 280, 244, 138, 210, 167, 129, 254, 167, 194, 191, 128, 191, 144, 184, 330, 216, 212, 142, 216, 197, 231, 133, 205, 192, 195, 243, 224, 137, 234, 171, 176, 249, 222, 234, 191])

In [79]:
alpha = 0.1

In [80]:
t_stat,p_value = ttest_1samp(data,190)

In [81]:
p_value

0.17797783112301213

In [82]:
if p_value < alpha:
    print('Reject H0')
else:
    print('Fail to Reject H0')

Fail to Reject H0


When smokers smoke, nicotine is transformed into cotinine, which can be tested.

The average cotinine level in a group of 50 smokers was 243.5 ng ml.

Assuming that the standard deviation is known to be 229.5 ng ml, at 95 % confidence, test the assertion that the mean cotinine level of all smokers is equal to 300.0 ng ml.

In [83]:
z_stat = (300.0-243.5)/(229.5/np.sqrt(50))

In [84]:
norm.cdf(z_stat)

0.9591413404242518